spring:
    application:
        name: trace-3
    rabbitmq:
        host: 10.150.157.96
        port: 5672
        username: admin
        password: admin
    zipkin:
        base-url: http://eureka-peer1:19411
    sleuth:
        sampler:
            percentage: 0.1 #抽样比例
server:
    port: 19103

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-peer1:10001/eureka/



## log trace detail
#logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG