spring:
    application:
        name: eureka-consumer-feign
server:
    port: 20103

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-peer1:10001/eureka/

logging:
    file: logs/${spring.application.name}.log
