spring:
    application:
        name: eureka-service-provider
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-peer1:10001/eureka/

---
spring:
    profiles: dev # not standalone
server:
    port: 20001
logging:
    file: logs/${spring.application.name}-${spring.profiles}.log

---
spring:
    profiles: test # not standalone
server:
    port: 20002
logging:
    file: logs/${spring.application.name}-${spring.profiles}.log


#eureka.instance.prefer-ip-address=true

# ½¡¿µ¼ì²é
#eureka.client.healthcheck.enabled=true

# Ëæ»ú¶Ë¿ÚÅäÖÃ
#eureka.instance.instance-id=${spring.application.name}:${random.int}
#server.port=0
#server.port=${random.int[10000,19999]}
