spring:
    application:
        name: zipkin-server-stream
    rabbitmq:
        host: 10.150.157.96
        port: 5672
        username: admin
        password: admin
server:
    port: 19412



eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-peer1:10001/eureka/

logging:
    file: ${spring.application.name}.log