spring:
    application:
        name: eureka-consumer-ribbon-hystrix
    rabbitmq:
        host: 10.150.157.96
        port: 5672
        username: admin
        password: admin
server:
    port: 20111

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-peer1:10001/eureka/

logging:
    file: logs/${spring.application.name}.log
