spring:
    application:
        name: eureka-consumer
server:
    port: 20101

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-peer1:10001/eureka/

logging:
    file: logs/${spring.application.name}.log

service:
    provider:
        name: eureka-service-provider
